ktor:
  deployment:
    port: 8090
  application:
    modules:
      - com.example.MainKt.module

jwt:
    secret: ${JWT_SECRET}
    issuer: "bus-station-backend-app"
    realm: "bus-station"

database:
  dbType: sqlite
  url: "jdbc:sqlite:./my_database.db"
  driverClassName: "org.sqlite.JDBC"
  maxPoolSize: 1